import { resolveArtwork } from "./artwork";
import { renderSignSvg } from "./svg";
import type { TrafficSign } from "./types";

function us(sign: Omit<TrafficSign, "jurisdiction" | "license" | "id" | "artwork" | "src">): TrafficSign {
  const art = resolveArtwork("US-CA", sign.code);
  return {
    ...sign,
    id: `US-CA-${sign.code}`,
    jurisdiction: "US-CA",
    license: art.license,
    src: art.src,
    artwork: art.kind,
  };
}

export const US_SIGNS: TrafficSign[] = [
  us({
    code: "R1-1",
    category: "priority",
    shape: "mutcd-stop",
    role: "stop",
    roadText: "STOP",
    name: { en: "Stop", pl: "Stop", ru: "Стоп" },
    meaning: {
      en: "Come to a full stop, then proceed when it is your turn.",
      pl: "Zatrzymaj się całkowicie, potem jedź gdy twoja kolej.",
      ru: "Полная остановка, затем движение когда ваша очередь.",
    },
    svg: renderSignSvg("mutcd-stop", "none"),
  }),
  us({
    code: "R1-2",
    category: "priority",
    shape: "mutcd-yield",
    role: "yield",
    name: { en: "Yield", pl: "Ustąp", ru: "Уступите" },
    meaning: {
      en: "Slow down and yield to other traffic.",
      pl: "Zwolnij i ustąp pierwszeństwa.",
      ru: "Замедлитесь и уступите дорогу.",
    },
    svg: renderSignSvg("mutcd-yield", "none"),
  }),
  ...[25, 30, 35, 40, 45, 50, 55, 65].map((speed) =>
    us({
      code: `R2-1-${speed}`,
      category: "prohibitory",
      shape: "mutcd-speed-rect",
      role: "none",
      name: { en: `Speed limit ${speed}`, pl: `Limit ${speed} mph`, ru: `Лимит ${speed} миль/ч` },
      meaning: {
        en: `Do not exceed ${speed} mph.`,
        pl: `Nie przekraczaj ${speed} mph.`,
        ru: `Не превышайте ${speed} миль/ч.`,
      },
      svg: renderSignSvg("mutcd-speed-rect", "speed", { speed }),
    }),
  ),
  us({
    code: "W1-1",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "Curve", pl: "Zakręt", ru: "Поворот" },
    meaning: {
      en: "A curve is ahead.",
      pl: "Zakręt przed tobą.",
      ru: "Впереди поворот.",
    },
    svg: renderSignSvg("mutcd-diamond", "curve-right"),
  }),
  us({
    code: "W2-1",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "Crossroad", pl: "Skrzyżowanie", ru: "Перекрёсток" },
    meaning: {
      en: "An intersection is ahead.",
      pl: "Skrzyżowanie przed tobą.",
      ru: "Впереди перекрёсток.",
    },
    svg: renderSignSvg("mutcd-diamond", "cross"),
  }),
  us({
    code: "W11-2",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "Pedestrian", pl: "Piesi", ru: "Пешеходы" },
    meaning: {
      en: "Watch for pedestrians.",
      pl: "Uwaga na pieszych.",
      ru: "Осторожно, пешеходы.",
    },
    svg: renderSignSvg("mutcd-diamond", "pedestrian"),
  }),
  us({
    code: "W3-3",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "Signal ahead", pl: "Sygnalizacja", ru: "Светофор" },
    meaning: {
      en: "Traffic signals ahead.",
      pl: "Sygnalizacja świetlna.",
      ru: "Впереди светофор.",
    },
    svg: renderSignSvg("mutcd-diamond", "lights"),
  }),
  us({
    code: "W8-5",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "Slippery when wet", pl: "Ślisko", ru: "Скользко" },
    meaning: {
      en: "Pavement may be slippery.",
      pl: "Nawierzchnia może być śliska.",
      ru: "Покрытие может быть скользким.",
    },
    svg: renderSignSvg("mutcd-diamond", "slippery"),
  }),
  us({
    code: "R5-1",
    category: "prohibitory",
    shape: "mutcd-do-not-enter",
    role: "none",
    name: { en: "Do not enter", pl: "Zakaz wjazdu", ru: "Въезд запрещён" },
    meaning: {
      en: "Do not enter.",
      pl: "Nie wjeżdżaj.",
      ru: "Въезд запрещён.",
    },
    svg: renderSignSvg("mutcd-do-not-enter", "none"),
  }),
  us({
    code: "R3-1",
    category: "prohibitory",
    shape: "prohibitory-circle",
    role: "none",
    name: { en: "No left turn", pl: "Zakaz skrętu w lewo", ru: "Налево нельзя" },
    meaning: {
      en: "Left turns are forbidden.",
      pl: "Zakaz skrętu w lewo.",
      ru: "Поворот налево запрещён.",
    },
    svg: renderSignSvg("prohibitory-circle", "no-left"),
  }),
  us({
    code: "R3-2",
    category: "prohibitory",
    shape: "prohibitory-circle",
    role: "none",
    name: { en: "No right turn", pl: "Zakaz skrętu w prawo", ru: "Направо нельзя" },
    meaning: {
      en: "Right turns are forbidden.",
      pl: "Zakaz skrętu w prawo.",
      ru: "Поворот направо запрещён.",
    },
    svg: renderSignSvg("prohibitory-circle", "no-right"),
  }),
  us({
    code: "W11-1",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "Bicycle", pl: "Rowerzyści", ru: "Велосипедисты" },
    meaning: {
      en: "Bicycles may be present.",
      pl: "Możliwi rowerzyści.",
      ru: "Возможны велосипедисты.",
    },
    svg: renderSignSvg("mutcd-diamond", "bike"),
  }),
  us({
    code: "W8-1",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "Bump", pl: "Próg", ru: "Неровность" },
    meaning: {
      en: "A bump is ahead.",
      pl: "Próg przed tobą.",
      ru: "Впереди неровность.",
    },
    svg: renderSignSvg("mutcd-diamond", "bump"),
  }),
  us({
    code: "W1-2",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "Reverse curve", pl: "Podwójny zakręt", ru: "Обратный поворот" },
    meaning: {
      en: "A reverse curve is ahead.",
      pl: "Seria zakrętów.",
      ru: "Впереди обратный поворот.",
    },
    svg: renderSignSvg("mutcd-diamond", "double-curve"),
  }),
  us({
    code: "W3-1",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "Stop ahead", pl: "STOP przed tobą", ru: "STOP впереди" },
    meaning: {
      en: "A stop sign is ahead.",
      pl: "Znak STOP przed tobą.",
      ru: "Впереди знак STOP.",
    },
    svg: renderSignSvg("mutcd-diamond", "exclaim"),
  }),
  us({
    code: "W4-1",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "Merge", pl: "Włączenie się", ru: "Слияние" },
    meaning: {
      en: "Traffic merges from the right.",
      pl: "Włączenie ruchu z prawej.",
      ru: "Слияние справа.",
    },
    svg: renderSignSvg("mutcd-diamond", "side-right"),
  }),
  us({
    code: "W10-1",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "Railroad crossing", pl: "Przejazd kolejowy", ru: "Железнодорожный переезд" },
    meaning: {
      en: "A railroad crossing is ahead.",
      pl: "Przejazd kolejowy przed tobą.",
      ru: "Впереди железнодорожный переезд.",
    },
    svg: renderSignSvg("mutcd-diamond", "rail"),
  }),
  us({
    code: "W11-3",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "Deer crossing", pl: "Zwierzęta", ru: "Олени" },
    meaning: {
      en: "Watch for animals.",
      pl: "Uwaga na zwierzęta.",
      ru: "Осторожно, животные.",
    },
    svg: renderSignSvg("mutcd-diamond", "deer"),
  }),
  us({
    code: "S1-1",
    category: "warning",
    shape: "mutcd-diamond",
    role: "none",
    name: { en: "School", pl: "Szkoła", ru: "Школа" },
    meaning: {
      en: "A school zone is ahead.",
      pl: "Strefa szkoły.",
      ru: "Впереди школьная зона.",
    },
    svg: renderSignSvg("mutcd-diamond", "children"),
  }),
  us({
    code: "R4-7",
    category: "mandatory",
    shape: "mandatory-circle",
    role: "none",
    name: { en: "Keep right", pl: "Trzymaj się prawej", ru: "Держитесь правее" },
    meaning: {
      en: "Keep to the right of the obstruction.",
      pl: "Omijaj przeszkodę z prawej.",
      ru: "Объезжайте препятствие справа.",
    },
    svg: renderSignSvg("mandatory-circle", "arrow-right"),
  }),
  us({
    code: "R6-1",
    category: "information",
    shape: "info-rectangle",
    role: "none",
    name: { en: "One way", pl: "Jednokierunkowa", ru: "Одностороннее" },
    meaning: {
      en: "One-way street.",
      pl: "Ulica jednokierunkowa.",
      ru: "Одностороннее движение.",
    },
    svg: renderSignSvg("info-rectangle", "one-way"),
  }),
];
